# Generated by Django 4.2.6 on 2025-10-02 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import media_api.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=media_api.models.user_directory_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Изображение"),
                            ("video", "Видео"),
                            ("document", "Документ"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Исходное имя файла"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="Размер файла (байты)"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME тип"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичный доступ"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Загруженный файл",
                "verbose_name_plural": "Загруженные файлы",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "uploadedfile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_api.uploadedfile",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ширина"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Высота"
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
            bases=("media_api.uploadedfile",),
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "uploadedfile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_api.uploadedfile",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Длительность (секунды)"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=media_api.models.user_directory_path,
                        verbose_name="Миниатюра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
            },
            bases=("media_api.uploadedfile",),
        ),
    ]
