# Generated by Django 4.2.6 on 2024-11-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
