# Generated by Django 4.2.6 on 2024-11-09 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatapp", "0002_alter_room_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Название комнаты"),
        ),
        migrations.AlterField(
            model_name="room",
            name="online",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=models.CharField(max_length=128, verbose_name="URL-адрес"),
        ),
    ]
