# Generated by Django 4.2.6 on 2024-11-09 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatapp", "0003_alter_room_name_alter_room_online_alter_room_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="online",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
