# Generated by Django 4.2.6 on 2025-04-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0006_userchat"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
