# Generated by Django 4.2.6 on 2025-04-22 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0007_privatemessage_is_read"),
    ]

    operations = [
        migrations.RenameField(
            model_name="privatemessage",
            old_name="is_read",
            new_name="read",
        ),
        migrations.DeleteModel(
            name="IndexView",
        ),
    ]
