# Generated by Django 4.2.6 on 2025-05-22 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatapp", "0009_privatechatroom_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="recipient",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
