# Generated by Django 4.2.6 on 2025-06-05 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0010_privatemessage_recipient"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserChat",
        ),
    ]
