# Generated by Django 4.2.6 on 2025-07-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0001_squashed_0011_delete_userchat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privatemessage",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddIndex(
            model_name="privatemessage",
            index=models.Index(
                fields=["room", "timestamp"], name="chatapp_pri_room_id_8f2feb_idx"
            ),
        ),
    ]
