# Generated by Django 4.2.6 on 2025-10-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0012_alter_privatemessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="media_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="media_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="media_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="media_type",
            field=models.CharField(
                choices=[("text", "Text"), ("image", "Image"), ("video", "Video")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="privatemessage",
            index=models.Index(
                fields=["media_hash"], name="chatapp_pri_media_h_c1a805_idx"
            ),
        ),
    ]
