# Generated by Django 4.2.6 on 2025-10-04 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("media_api", "0001_initial"),
        ("chatapp", "0013_privatemessage_media_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="media_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="media_api.uploadedfile",
                verbose_name="Медиафайл",
            ),
        ),
        migrations.AddIndex(
            model_name="privatemessage",
            index=models.Index(
                fields=["media_file"], name="chatapp_pri_media_f_0253b3_idx"
            ),
        ),
    ]
