# Generated by Django 4.2.6 on 2025-10-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0014_privatemessage_media_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatemessage",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("document", "Document"),
                    ("other", "Other"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
