# Generated by Django 4.2.6 on 2025-10-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0015_alter_privatemessage_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
