# Generated by Django 4.2.6 on 2025-10-20 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatapp", "0016_privatemessage_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время удаления"
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Удалено пользователем",
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="is_deleted",
            field=models.BooleanField(
                default=False, verbose_name="Помечено как удаленное"
            ),
        ),
    ]
