# Generated by Django 4.2.6 on 2025-10-20 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "chatapp",
            "0017_privatemessage_deleted_at_privatemessage_deleted_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDeletedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время удаления"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_deletions",
                        to="chatapp.privatemessage",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deleted_message_relations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользовательское удаление сообщения",
                "verbose_name_plural": "Пользовательские удаления сообщений",
                "indexes": [
                    models.Index(
                        fields=["user", "message"],
                        name="chatapp_use_user_id_16ba14_idx",
                    )
                ],
                "unique_together": {("user", "message")},
            },
        ),
        migrations.CreateModel(
            name="MessageDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletions",
                        to="chatapp.privatemessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_deletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["message", "user"],
                        name="chatapp_mes_message_456303_idx",
                    ),
                    models.Index(
                        fields=["user", "deleted_at"],
                        name="chatapp_mes_user_id_c2efd6_idx",
                    ),
                ],
                "unique_together": {("message", "user")},
            },
        ),
    ]
