# Generated by Django 4.2.6 on 2025-10-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0018_userdeletedmessage_messagedeletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="reply_to_media_type",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Тип медиа исходного сообщения",
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="reply_to_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chatapp.privatemessage",
                verbose_name="Ответ на сообщение",
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="reply_to_message_text",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Текст сообщения, на которое отвечаем",
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="reply_to_sender_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Имя отправителя исходного сообщения",
            ),
        ),
        migrations.AddIndex(
            model_name="privatemessage",
            index=models.Index(
                fields=["reply_to_message"], name="chatapp_pri_reply_t_50f636_idx"
            ),
        ),
    ]
