# Generated by Django 4.2.6 on 2025-04-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0002_alter_customuser_email_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("male", "Мужчина"), ("female", "Женщина")],
                default="male",
                max_length=20,
            ),
        ),
    ]
