# Generated by Django 4.2.6 on 2025-06-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0003_customuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="online"),
        ),
    ]
