# Generated by Django 4.2.6 on 2025-06-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0004_customuser_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_joined",
            field=models.DateTimeField(auto_now=True, verbose_name="<UNK> <UNK>"),
        ),
    ]
