# Generated by Django 4.2.6 on 2025-06-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0005_customuser_last_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_online",
            field=models.CharField(
                choices=[("online", "в сети"), ("offline", "не в сети")],
                default="offline",
                max_length=20,
            ),
        ),
    ]
