# Generated by Django 4.2.6 on 2025-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0001_squashed_0006_alter_customuser_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
