# Generated by Django 4.2.6 on 2025-06-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0001_squashed_0006_alter_customuser_is_online"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="age",
        ),
        migrations.AddField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="День рождения"),
        ),
    ]
