# Generated by Django 4.2.6 on 2025-06-06 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0007_alter_customuser_age"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="age",
            new_name="years",
        ),
    ]
