# Generated by Django 4.2.6 on 2025-07-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0007_remove_customuser_age_customuser_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Код подтверждения email",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_code_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Срок действия кода подтверждения"
            ),
        ),
    ]
