# Generated by Django 4.2.6 on 2025-08-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0008_customuser_verification_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="expo_push_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
