# Generated by Django 4.2.6 on 2025-08-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0009_customuser_expo_push_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_reset_token",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Токен для сброса пароля",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="password_reset_uid",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="UID для сброса пароля",
            ),
        ),
    ]
