# Generated by Django 4.2.6 on 2025-08-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0010_customuser_password_reset_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
