# Generated by Django 4.2.6 on 2025-06-05 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photo_alboms.models


class Migration(migrations.Migration):
    replaces = [
        ("photo_alboms", "0001_initial"),
        ("photo_alboms", "0002_photo_user_alter_photo_album"),
        ("photo_alboms", "0003_alter_photo_album_alter_photo_user"),
        ("photo_alboms", "0004_alter_photo_image"),
        ("photo_alboms", "0005_photoalbum_hidden_flag"),
        ("photo_alboms", "0006_alter_photoalbum_hidden_flag"),
        ("photo_alboms", "0007_alter_photo_image"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("hidden_flag", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to=photo_alboms.models.save_photos)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="photo_alboms.photoalbum",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
