# Generated by Django 4.2.6 on 2025-03-21 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photo_alboms", "0002_photo_user_alter_photo_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="photo_alboms.photoalbum",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
