# Generated by Django 4.2.6 on 2025-03-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_alboms", "0003_alter_photo_album_alter_photo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.FileField(upload_to="my_files/"),
        ),
    ]
