# Generated by Django 4.2.6 on 2025-03-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_alboms", "0004_alter_photo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoalbum",
            name="hidden_flag",
            field=models.BooleanField(default=True),
        ),
    ]
