# Generated by Django 4.2.6 on 2025-04-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_alboms", "0005_photoalbum_hidden_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoalbum",
            name="hidden_flag",
            field=models.BooleanField(default=False),
        ),
    ]
