# Generated by Django 4.2.6 on 2025-04-21 04:49

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        unique=True,
                        verbose_name="URL-адрес",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("del", "Delete"),
                            ("pu", "Published"),
                            ("wi", "Withdrawn"),
                        ],
                        default="pu",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "preamble",
                    django_ckeditor_5.fields.CKEditor5Field(
                        max_length=1024, verbose_name="Преамбула"
                    ),
                ),
                ("content", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Отредактировано"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="URL-адрес",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ключевые слова"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("del", "Delete"),
                            ("pu", "Published"),
                            ("wi", "Withdrawn"),
                        ],
                        default="pu",
                        max_length=3,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ("-updated",),
            },
        ),
    ]
