# Generated by Django 4.2.6 on 2024-10-24 08:25

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="preamble",
            field=django_ckeditor_5.fields.CKEditor5Field(
                max_length=1024, verbose_name="Преамбула"
            ),
        ),
    ]
