# Generated by Django 4.2.6 on 2025-04-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_alter_article_content_alter_article_preamble"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("del", "Delete"), ("pu", "Published"), ("wi", "Withdrawn")],
                default="pu",
                max_length=3,
            ),
        ),
    ]
